version: '{build}'
skip_tags: true
image: Visual Studio 2019
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: kT0cfI8JdDdk7OBQtaARqgBfJkRGGgyqqHeFcZs1wIyOppSAeiUaF8Syxne/BM7W
  skip_symbols: true
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
